apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: airbnb-scoring
  annotations:
    github.com/project-slug: UnleashedMV/airbnb-scoring
spec:
  type: other
  lifecycle: unknown
  owner: guests
